version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo
    groups:
      development-dependencies:
        dependency-type: development
      astro:
        patterns:
          - "astro"
          - "@astro/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo
